ctest:
	cmake -B build && cmake --build build && ctest  --output-on-failure --test-dir build

ctest_verbose:
	cmake -B build && cmake --build build && ctest --verbose --output-on-failure --test-dir build
